apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gitlab-runner-1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gitlab-runner-1
    spec:
      containers:
        - image: gitlab/gitlab-runner:v1.11.5
          name: gitlab-runner-1
          volumeMounts:
            - mountPath: /etc/gitlab-runner
              name: config
      volumes:
        - name: config
          configMap:
            name: gitlab-runner-1
