apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: ingress-controller-svc
  labels:
    router: router 
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 80
  - port: 443
    name: https
    protocol: TCP
    targetPort: 443
  selector:
    router: router
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: 104.199.0.202
